spring:
  application:
    name: openshift-demo
  zipkin:
    base-url: ${BASE_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
debug: false

#bean:
#  message: 124



